### ISSUE TITLE
gmi send croaks on some sendmail arguments

### ISSUE THREAD

**Issue by skangas** [gauteh/lieer#139]
I'm running the current master branch, where I'm very happy to see that there is now support for sending emails.

With the following configuration in GNU Emacs:

```
  (setq sendmail-program (expand-file-name "~/src/lieer/gmi"))
  (setq message-sendmail-extra-arguments '("send" "-C" "~/.mail/account.gmail"))
```

I type M-x message-mail in Emacs, but upon sending the email, I get these errors:

```
usage: gmi [-h] [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver]
           [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
           [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
           {pull,push,send,sync,auth,init,set} ...
gmi: error: unrecognized arguments: -oi -f -t
```

I think Emacs is trying to pass some sendmail arguments, but lieer does not recognize them and croaks.  Maybe these arguments should be simply ignored?  I'm not sure.

Thanks in advance.

**Comment by skangas** [comment]
This might be relevant, quoted from the exim sendmail man page:

```
       -f <address>
                 This option sets the address of the envelope sender of a  lo‐
                 cally-generated  message (also known as the return path).

       -i        This option, which has the same effect as -oi, specifies that
                 a dot on a line by itself should not terminate  an  incoming,
                 non-SMTP message.

       -t        When Exim is receiving a locally-generated, non-SMTP  message
                 on its standard input, the -t option causes the recipients of
                 the message to be obtained from the To:, Cc:, and Bcc: header
                 lines  in  the message instead of from the command arguments.
                 The addresses are extracted before any rewriting takes  place
                 and the Bcc: header line, if present, is then removed.
```

**Comment by gauteh** [comment]
Yes, msmtp does the same. If any of those can be disabled in emacs config
that would be better, unless they are completely safe to ignore.

Do you know what those options are?

tir. 5. mai 2020, 16:57 skrev Stefan Kangas <notifications@github.com>:

**Comment by skangas** [comment]
Thanks for your prompt reply here, I really appreciate it.

> Yes, msmtp does the same. If any of those can be disabled in emacs config that would be better, unless they are completely safe to ignore. Do you know what those options are?

My old configuration for msmtp was simply:

`
(setq sendmail-program "/usr/bin/msmtp")
`

So I'm assuming msmtp in fact *does* handle the above arguments? Hmm, actually, looking at the msmtp man page, I see:

```
              -f, --from=address
                     Set the envelope-from address.
```
```
              -t, --read-recipients
                     Read recipient addresses from the To, Cc, and Bcc headers
                     of  the  mail  in addition to the recipients given on the
                     command line.
```

And:

```
       The following options are accepted but ignored for sendmail compatibil‐
       ity:
       -Btype, -bm, -G, -hN, -i, -L tag, -m, -n, -O option=value, -ox value
```

What do you think?

PS. To answer your question, I can't find the knob to disable these flags in Emacs.  Maybe it's just assumed that whatever program is used as a sendmail replacement will support those flags?

**Comment by gauteh** [comment]
Lets ignore -oi, -t is always implied - don't know what to do about that.
So ignore. -f should maybe be implemented?

tir. 5. mai 2020, 17:20 skrev Stefan Kangas <notifications@github.com>:

**Comment by skangas** [comment]
I'm not sure I understand the full implications of using or not using -f, so I can't give an informed opinion. For now one can use this fire-escape in Emacs to not pass it:

`
(setq message-sendmail-f-is-evil t)
`

It seems that this was added as a work-around for limitions in msmtp or some other sendmail replacement at one point. But at least msmtp has added support for that flag since. So I suppose one could consider that as a nice feature to have, but not critical? I'm not sure.

The rest sounds good to me.  If -t is always implied, maybe its better to just ignore it (and document it as such)?

**Comment by gauteh** [comment]
Yeah, ideally we should maybe require -t but that seems annoying. Better to
just document.

tir. 5. mai 2020, 17:59 skrev Stefan Kangas <notifications@github.com>:

**Comment by skangas** [comment]
I'm seeing the following command line from Emacs:

`
gmi -oi send -C ~/.mail/account.gmail -t
`

And with #140, I get:

`
gmi send: error: argument -t: expected one argument
`

This is fixed if -t is changed to `action='store_true'` instead of `type = str`.  With that changed, I'm still getting this:

`
gmi: error: unrecognized arguments: -oi
`

Which I suppose is because -oi comes before send, and would be fixed if -oi is ignored for the main argparser. But thinking about this, an external application could pass these arguments in any order really, so maybe they should be ignored no matter the order? Not sure if that's easy to do with argparse.

Thanks again for the excellent response time here, and the package in general which is highly useful.

**Comment by gauteh** [comment]
Stefan Kangas writes on May 5, 2020 19:56:
> This is fixed if -t is changed to `action='store_true'` instead of
> `type = str`.  With that changed, I'm still getting this:

Fixed.

>
> `
> gmi: error: unrecognized arguments: -oi
> `
>
> Which I suppose is because -oi comes before send, and would be fixed
> if -oi is ignored for the main argparser. But thinking about this, an
> external application could pass these arguments in any order really,
> so maybe they should be ignored no matter the order? Not sure if
> that's easy to do with argparse.

Moved to common parser, please check if that helps.

**Comment by skangas** [comment]
> Moved to common parser, please check if that helps.

Thanks.  Using your most recent commit, I'm still getting this error unfortunately:

```
gmi: error: unrecognized arguments: -oi
```

**Comment by gauteh** [comment]
Seems impossible to do through argparse, fixing in sys.argv directly.

**Comment by skangas** [comment]
The issue seems to be that we have the argument before the subparser action.  I get this on current master:

```
$ ~/src/lieer/gmi -s sync
usage: gmi [-h] [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver] [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]] [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}] {pull,push,send,sync,auth,init,set} ...
gmi: error: unrecognized arguments: -s
```

Possibly relevant discussion here: https://stackoverflow.com/questions/46962065/add-top-level-argparse-arguments-after-subparser-args

**Comment by skangas** [comment]
> Seems impossible to do through argparse, fixing in sys.argv directly.

Works like a charm. Good idea to circumvent the argparse machinery for this.

Thanks!
