### ISSUE TITLE
'%s' does not contain valid maildir delimiter

### ISSUE THREAD

**Issue by archenemies** [gauteh/lieer#142]
When I run `gmi sync`, I get a number of lines like this:

    '%s' does not contain valid maildir delimiter, correct file name extension, or does not seem to have a valid GID, ignoring.

It started out with just a few lines, but now (several months later) the error text is repeated 10 or 20 times with each call to `gmi sync`.

Everything else seems to work properly, is there a way to fix the errors (or even just to find out what they are referring to)?

**Comment by gauteh** [comment]
archenemies writes on May 5, 2020 23:58:
> When I run `gmi sync`, I get a number of lines like this:
>
>     '%s' does not contain valid maildir delimiter, correct file name
>     extension, or does not seem to have a valid GID, ignoring.
>
> It started out with just a few lines, but now (several months later)
> the error text is repeated 10 or 20 times with each call to `gmi
> sync`.
>
> Everything else seems to work properly, is there a way to fix the
> errors (or even just to find out what they are referring to)?
>

I forgot to print the offending file name, I just pushed to master a
change that should show the file name causing trouble. Let me know if
that does not help solve the issue. I am guessing that some stray files
made it into your maildir.

**Comment by archenemies** [comment]
Thank you, it was some stuff in `gmail/new` ... don't know how it got there, but all spam

**Comment by archenemies** [comment]
I'm still getting a lot of these errors, and they are from files that have just been downloaded by `gmi`.

    '192013d36c52b28b' does not contain valid maildir delimiter, correct file name extension, or does not seem to have a valid GID, ignoring.

    $ ls -al mail/*/192013d36c52b28b
    -rw-r--r-- 1 me me 22903 Sep 17 11:27 mail/new/192013d36c52b28b

Some of them are definitely not spam. What is a GID? The code doesn't contain a definition of the term GID.

It looks like your code is expecting all Maildir files to end with ":2,"? But files in 'new' don't have this suffix yet.

    def __filename_to_gid__(self, fname):
        ext = ""
        if self.config.file_extension:
            ext = "." + self.config.file_extension
        ext += ":2,"

        f = fname.rfind(ext)
        if f > 5:
            return fname[:f]
        else:
            print(
                "'%s' does not contain valid maildir delimiter, correct file name extension, or does not seem to have a valid GID, ignoring."
                % fname
            )
            return None

**Comment by gauteh** [comment]
Did you close the issue?

**Comment by gauteh** [comment]
I'm not sure about the logic behind the `f > 5`. All files by lieer should have the ":2," extension, are these files put in there by some other imap tool?

**Comment by archenemies** [comment]
No, the mail is only imported by lieer. All the files in "new/" have no extension, all files in "cur/" end with ":2" or ":2,S". What is a GID?

**Comment by gauteh** [comment]
The google ID: 192013d36c52b28b

**Comment by gauteh** [comment]
lieer stores new messages in `cur`: https://github.com/gauteh/lieer/blob/master/lieer/local.py#L594, I tried to grep the whole code base, and it only seems like we read from `new` -- never write?

**Comment by archenemies** [comment]
I don't know, but according to the Maildir article on Wikipedia, files in `new/` don't need to have any extension or suffix, because the extension is added when they are moved into `cur/`. Is it possible that Notmuch is moving stuff into `new/`? I asked it to give new messages a 'new' label, and to mirror the Notmuch tags and Maildir flags for each message file. Frankly I wouldn't mind if it moved stuff into `new/`; and I would have expected Lieer to support that. Maybe re-open the issue?
